name: workflow

on:
  push:
    branches:
      - main

    paths-ignore:
      - "README.md"
      - "setup.py"
      - "template.py"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code # Linting is the process of checking your code for style and syntax errors.
        run: pip install flake8 && flake8 .

      - name: Run unit tests
        run: python -B -m pytest tests/unit

      - name: Run integration tests
        run: python -B -m pytest tests/integration
