name: worflow

on:
  push:
    branches:
      - main

    paths-ignore:
      - "README.md"
      - "setup.py"
      - "template.py"
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Lint code
        run: pip install flake8 && flake8 . || true

      - name: Run unit tests
        run: python -B -m pytest tests/unit

      - name: Run integration tests
        run: python -B -m pytest tests/integration
